spring:
  application:
    name: game-marketplace
  output:
    ansi:
      enabled: detect
  profiles:
    active:
      - local
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    dev.levi.gamemarketplace: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: WARN

jwt:
  secret: "troque-isso-por-uma-chave-forte-de-pelo-menos-32-caracteres"
  expiration-ms: 3600000 # 1h
